<a href="https://colab.research.google.com/github/Almodovare/Notebooks/blob/main/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B_%D1%81%D0%BE%D0%BF%D1%80%D1%8F%D0%B6%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.19.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 27.5 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.4

In [5]:
import pyreadstat
import pandas as pd
from scipy.stats import chi2_contingency

In [16]:
df_1 = pd.read_spss('/content/База_ДНК (08.04).sav')
df_1

,ID,SEX,AGE,FO,TIP,dnk1,dnk1_1d,dnk1_2d,dnk2,dnk3,...,DETI_1,DETI_2,DETI_3,DETI_4,DETI_5,DETI_6,PROF1,PROF2,PROF3,weight1
0,0afeda8dfe8ce1bc,Мужской,53.0,Северо-Кавказский федеральный округ,Город с численностью от 100 тысяч до 500 тысяч,"Скорее положительно (поясните, почему?)",Для защиты ребенка и матери / безопасность,NaN,Укреплять отношения в паре,Согласился бы,...,Есть дети 18 лет и старше,Есть дети от 7 до 17 лет включительно,NaN,NaN,NaN,NaN,Самозанятый,NaN,Строительство Включает в том числе: архитектур...,0.536306
1,0afec438540ce727,Мужской,72.0,Приволжский федеральный округ,Село,"Скорее отрицательно (поясните, почему?)",NaN,Навредит ребенку и матери,Укреплять отношения в паре,Согласился бы,...,Есть дети 18 лет и старше,NaN,NaN,NaN,NaN,NaN,Неработающий пенсионер (в том числе по инвалид...,NaN,NaN,1.310878
2,0afec0aff0cce79d,Женский,60.0,Приволжский федеральный округ,Город с численностью от 100 тысяч до 500 тысяч,"Скорее положительно (поясните, почему?)",Во избежание спорных моментов / юридические во...,NaN,Затрудняюсь ответить,Согласился бы,...,Есть дети 18 лет и старше,Есть дети от 7 до 17 лет включительно,NaN,NaN,NaN,NaN,"Работаю по договОру, контракту в найме (за иск...","Я работаю в КОММЕРЧЕСКОЙ организации, ее цель ...","Общественное питание, ресторанный и гостиничны...",1.088766
3,0afed315418cefb3,Мужской,59.0,Приволжский федеральный округ,Город с численностью жителей миллион и более ч...,Затрудняюсь ответить,NaN,NaN,Никак не влиять на отношения,Скорее согласился бы,...,Есть дети 18 лет и старше,NaN,NaN,NaN,NaN,NaN,Неработающий пенсионер (в том числе по инвалид...,NaN,NaN,0.399851
4,0afece9f650ce912,Женский,72.0,Приволжский федеральный округ,Город с численностью от 50 тысяч до 100 тысяч,"Скорее положительно (поясните, почему?)",Бывает путают детей в роддамах / меняют,NaN,Никак не влиять на отношения,Согласился бы,...,Есть дети 18 лет и старше,NaN,NaN,NaN,NaN,NaN,Неработающий пенсионер (в том числе по инвалид...,NaN,NaN,1.654717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1603,0afecb1c284ce377,Женский,41.0,Приволжский федеральный округ,Село,Затрудняюсь ответить,NaN,NaN,Никак не влиять на отношения,Затрудняюсь ответить,...,Есть дети от 7 до 17 лет включительно,Есть дети 18 лет и старше,NaN,NaN,NaN,NaN,"Временно не работаю, безработный",NaN,NaN,1.936879
1604,0afefcfe11cce19f,Женский,41.0,Центральный федеральный округ,Город с численностью от 100 тысяч до 500 тысяч,Затрудняюсь ответить,NaN,NaN,Затрудняюсь ответить,Затрудняюсь ответить,...,Нет детей,NaN,NaN,NaN,NaN,NaN,"Временно не работаю, безработный",NaN,NaN,1.057767
1605,0afecadf074ce250,Женский,45.0,Приволжский федеральный округ,Село,"Скорее отрицательно (поясните, почему?)",NaN,"Родители сами все знаю / мать знает, кто отец",Ослаблять отношения,Точно не согласился бы,...,Есть дети от 7 до 17 лет включительно,NaN,NaN,NaN,NaN,NaN,"Работаю по договОру, контракту в найме (за иск...","Я работаю в КОММЕРЧЕСКОЙ организации, ее цель ...","Сельское, лесное хозяйство, охота, рыболовство...",1.620950
1606,0afec64c8e8ce1da,Женский,67.0,Приволжский федеральный округ,Село,Скорее безразлично,NaN,NaN,Затрудняюсь ответить,Точно не согласился бы,...,Есть дети 18 лет и старше,NaN,NaN,NaN,NaN,NaN,Неработающий пенсионер (в том числе по инвалид...,NaN,NaN,2.134844
1607,0afec7d8cc8ce71a,Женский,62.0,Приволжский федеральный округ,Село,"Скорее положительно (поясните, почему?)",Бывают разные ситуации,NaN,Укреплять отношения в паре,Затрудняюсь ответить,...,Есть дети 18 лет и старше,NaN,NaN,NaN,NaN,NaN,Неработающий пенсионер (в том числе по инвалид...,NaN,NaN,2.134844

In [6]:
df, meta = pyreadstat.read_sav("/content/База_ДНК (08.04).sav")

In [9]:
df

,ID,SEX,AGE,FO,TIP,dnk1,dnk1_1d,dnk1_2d,dnk2,dnk3,...,DETI_1,DETI_2,DETI_3,DETI_4,DETI_5,DETI_6,PROF1,PROF2,PROF3,weight1
0,0afeda8dfe8ce1bc,1.0,53.0,4.0,3.0,1.0,5.0,NaN,1.0,1.0,...,3.0,2.0,NaN,NaN,NaN,NaN,9.0,NaN,3.0,0.536306
1,0afec438540ce727,1.0,72.0,5.0,7.0,2.0,NaN,13.0,1.0,1.0,...,3.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.310878
2,0afec0aff0cce79d,2.0,60.0,5.0,3.0,1.0,4.0,NaN,99.0,1.0,...,3.0,2.0,NaN,NaN,NaN,NaN,7.0,1.0,17.0,1.088766
3,0afed315418cefb3,1.0,59.0,5.0,1.0,99.0,NaN,NaN,3.0,2.0,...,3.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.399851
4,0afece9f650ce912,2.0,72.0,5.0,4.0,1.0,1.0,NaN,3.0,1.0,...,3.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.654717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1603,0afecb1c284ce377,2.0,41.0,5.0,7.0,99.0,NaN,NaN,3.0,99.0,...,2.0,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,1.936879
1604,0afefcfe11cce19f,2.0,41.0,1.0,3.0,99.0,NaN,NaN,99.0,99.0,...,97.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,1.057767
1605,0afecadf074ce250,2.0,45.0,5.0,7.0,2.0,NaN,9.0,2.0,4.0,...,2.0,NaN,NaN,NaN,NaN,NaN,7.0,1.0,2.0,1.620950
1606,0afec64c8e8ce1da,2.0,67.0,5.0,7.0,3.0,NaN,NaN,99.0,4.0,...,3.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.134844
1607,0afec7d8cc8ce71a,2.0,62.0,5.0,7.0,1.0,16.0,NaN,1.0,99.0,...,3.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.134844

In [10]:
meta

metadata_container(column_names=['ID', 'SEX', 'AGE', 'FO', 'TIP', 'dnk1', 'dnk1_1d', 'dnk1_2d', 'dnk2', 'dnk3', 'dnk4', 'TV', 'd1', 'EDU', 'DOHOD_0', 'DETI_1', 'DETI_2', 'DETI_3', 'DETI_4', 'DETI_5', 'DETI_6', 'PROF1', 'PROF2', 'PROF3', 'weight1'], column_labels=['Идентификатор респондента', 'Пол', 'Сколько полных лет Вам исполнилось?', 'Федеральный округ', 'Тип населенного пункта', 'dnk1. Сменим тему. В России предложили ввести обязательную процедуру ДНК-тестирования в родильных домах с согласия обоих родителей. По мнению авторов, нововведение обеспечит правовую защиту детей с первых дней жизни, например, облегчит назначение выпла', 'Скорее положительно (поясните, почему?)', 'Скорее отрицательно (поясните, почему?)', 'dnk2. Как Вы считаете, если ДНК-тест подтверждает отцовство, факт его проведения будет скорее…?', 'dnk3. А Вы согласились бы на проведение такого теста при рождении ребенка или нет?', 'dnk4. Представьте, что мужчина узнаёт, что ребенок, которого он воспитывал, не является его биологическим. Как, по Вашему мнению, ему следует поступить?', 'TV. Поговорим немного о Вас. Скажите, пожалуйста, Вы смотрите телевизор или нет? Если смотрите, то как часто?', 'd1. Скажите, пожалуйста, Вы пользуетесь интернетом? Если да, то как часто?', 'EDU. Какое у Вас образование?', 'DOHOD-0. Как бы Вы оценили в настоящее время материальное положение Вашей семьи – Вас и Ваших родственников, постоянно проживающих вместе с Вами?', 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'PROF_1. Скажите, пожалуйста, каково Ваше основное занятие в настоящий момент? Я зачитаю варианты ответов, а Вы выберите вариант, который подходит Вам.', 'PROF_2. В нашей стране существуют организации разных видов. Сейчас я зачитаю несколько вариантов, а Вы скажите, какой из них лучше соответствует организации / предприятию, где Вы работаете.', 'PROF_3. Скажите, к какой отрасли, сфере деятельности относится организация, в которой Вы работаете?', None], column_names_to_labels={'ID': 'Идентификатор респондента', 'SEX': 'Пол', 'AGE': 'Сколько полных лет Вам исполнилось?', 'FO': 'Федеральный округ', 'TIP': 'Тип населенного пункта', 'dnk1': 'dnk1. Сменим тему. В России предложили ввести обязательную процедуру ДНК-тестирования в родильных домах с согласия обоих родителей. По мнению авторов, нововведение обеспечит правовую защиту детей с первых дней жизни, например, облегчит назначение выпла', 'dnk1_1d': 'Скорее положительно (поясните, почему?)', 'dnk1_2d': 'Скорее отрицательно (поясните, почему?)', 'dnk2': 'dnk2. Как Вы считаете, если ДНК-тест подтверждает отцовство, факт его проведения будет скорее…?', 'dnk3': 'dnk3. А Вы согласились бы на проведение такого теста при рождении ребенка или нет?', 'dnk4': 'dnk4. Представьте, что мужчина узнаёт, что ребенок, которого он воспитывал, не является его биологическим. Как, по Вашему мнению, ему следует поступить?', 'TV': 'TV. Поговорим немного о Вас. Скажите, пожалуйста, Вы смотрите телевизор или нет? Если смотрите, то как часто?', 'd1': 'd1. Скажите, пожалуйста, Вы пользуетесь интернетом? Если да, то как часто?', 'EDU': 'EDU. Какое у Вас образование?', 'DOHOD_0': 'DOHOD-0. Как бы Вы оценили в настоящее время материальное положение Вашей семьи – Вас и Ваших родственников, постоянно проживающих вместе с Вами?', 'DETI_1': 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI_2': 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI_3': 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI_4': 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI_5': 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'DETI_6': 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?', 'PROF1': 'PROF_1. Скажите, пожалуйста, каково Ваше основное занятие в настоящий момент? Я зачитаю варианты ответов, а Вы выберите вариант, который подходит Вам.', 'PROF2': 'PROF_2. В нашей стране существуют организации разных видов. Сейчас я зачитаю несколько вариантов, а Вы скажите, какой из них лучше соответствует организации / предприятию, где Вы работаете.', 'PROF3': 'PROF_3. Скажите, к какой отрасли, сфере деятельности относится организация, в которой Вы работаете?', 'weight1': None}, file_encoding='UTF-8', file_label=None, number_columns=25, number_rows=1608, variable_value_labels={'SEX': {1.0: 'Мужской', 2.0: 'Женский'}, 'FO': {1.0: 'Центральный федеральный округ', 2.0: 'Северо-Западный федеральный округ', 3.0: 'Южный федеральный округ', 4.0: 'Северо-Кавказский федеральный округ', 5.0: 'Приволжский федеральный округ', 6.0: 'Уральский федеральный округ', 7.0: 'Сибирский федеральный округ', 8.0: 'Дальневосточный федеральный округ'}, 'TIP': {1.0: 'Город с численностью жителей миллион и более человек', 2.0: 'Город с численностью от 500 тысяч до 950 тысяч', 3.0: 'Город с численностью от 100 тысяч до 500 тысяч', 4.0: 'Город с численностью от 50 тысяч до 100 тысяч', 5.0: 'Город с численностью менее 50 тысяч', 6.0: 'Поселок городского типа', 7.0: 'Село'}, 'dnk1': {1.0: 'Скорее положительно (поясните, почему?)', 2.0: 'Скорее отрицательно (поясните, почему?)', 3.0: 'Скорее безразлично', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'dnk1_1d': {1.0: 'Бывает путают детей в роддамах / меняют', 2.0: 'В медицинских целях / выявление генетических болезней', 3.0: 'Важно для выплаты алиментов / избежание не выплаты алиментов', 4.0: 'Во избежание спорных моментов / юридические вопросы', 5.0: 'Для защиты ребенка и матери / безопасность', 6.0: 'Получение социальных выплат', 7.0: 'Определение отцовства / отец будет знать его ребенок или нет / знать, кто родитель / от кого ребенок', 8.0: 'Положительно отношусь / это правильно / полезно', 9.0: 'Если оба согласны, то пусть делают', 10.0: 'Есть случаи, когда отцы воспитывают не своих детей / женщины гуляют, обманывают', 11.0: 'Защита прав отцов', 12.0: 'Дети будут знать кто их родители', 13.0: 'Больше уверенности / доверия / если нечего скрывать / не будет сомнений', 14.0: 'Отцы должны принимать участие в жизни ребенка', 15.0: 'Меньше обмана / проблем', 16.0: 'Бывают разные ситуации', 17.0: 'Снимет кучу вопросов', 18.0: 'Родители будут знать, что это их ребенок', 19.0: 'Поможет в установлении личности', 20.0: 'Предотвратить измены / сохранение семей', 21.0: 'Предотвратить измены / сохранение семей', 98.0: 'Другое', 99.0: 'Затрудняюсь ответить'}, 'dnk1_2d': {1.0: 'В этом нет смысла / отрицательно отношусь', 2.0: 'Вмешательство в личную жизнь', 3.0: 'Есть доверие / уверенны друг в друге', 4.0: 'Трата бюджетных средств', 5.0: 'Сами должны решать нужен тест или нет / личное дело каждого', 6.0: 'Внесет разногласия в семью / увеличится количество разводов', 7.0: 'Не верю в корректность результата теста', 8.0: 'Дальнейшее использование данных / контроль над людьми', 9.0: 'Родители сами все знаю / мать знает, кто отец', 10.0: 'Против мучения ребенка', 11.0: 'Бывает суррогатное материнство', 12.0: 'Проводить только если необходимо / через суд', 13.0: 'Навредит ребенку и матери', 14.0: 'Главное ребенок родился / неважно чей', 98.0: 'Другое', 99.0: 'Затрудняюсь ответить'}, 'dnk2': {1.0: 'Укреплять отношения в паре', 2.0: 'Ослаблять отношения', 3.0: 'Никак не влиять на отношения', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'dnk3': {1.0: 'Согласился бы', 2.0: 'Скорее согласился бы', 3.0: 'Скорее не согласился бы', 4.0: 'Точно не согласился бы', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'dnk4': {1.0: 'Продолжать воспитывать ребенка, так как важнее сложившиеся отношения, отец – тот, кто воспитал', 2.0: 'Прекратить участие в жизни ребенка, так как биологическое родство принципиально важно', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'TV': {1.0: 'Смотрю более четырех часов ежедневно', 2.0: 'Ежедневно менее четырех часов в день', 3.0: 'Несколько раз в неделю', 4.0: 'Несколько раз в месяц', 5.0: 'Редко, но не менее одного раза в полгода', 6.0: 'Не смотрю', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'}, 'd1': {1.0: 'Провожу в интернете более четырех часов ежедневно', 2.0: 'Eжедневно менее четырех часов в день', 3.0: 'Несколько раз в неделю', 4.0: 'Несколько раз в месяц', 5.0: 'Редко, но не менее одного раза в полгода', 96.0: 'Не пользуюсь', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'}, 'EDU': {1.0: '(НЕ ЗАЧИТЫВАТЬ) Нет основного общего образования: не окончил 9 (раньше 8) классов', 2.0: 'Основное общее образование: окончил 9 (раньше 8) классов', 3.0: 'Среднее общее (10 или 11 классов школы с аттестатом)', 4.0: 'Среднее профессиональное (техникум, колледж, ПТУ)', 5.0: 'Незаконченное высшее (с 3-го курса вуза) или законченное высшее', 6.0: 'Два и более высших образования, ученая степень кандидата или доктора наук', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'DOHOD_0': {1.0: 'Очень хорошее', 2.0: 'Хорошее', 3.0: 'Среднее', 4.0: 'Плохое', 5.0: 'Очень плохое', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'}, 'DETI_1': {1.0: 'Есть дети до 6 лет включительно', 2.0: 'Есть дети от 7 до 17 лет включительно', 3.0: 'Есть дети 18 лет и старше', 97.0: 'Нет детей', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'DETI_2': {1.0: 'Есть дети до 6 лет включительно', 2.0: 'Есть дети от 7 до 17 лет включительно', 3.0: 'Есть дети 18 лет и старше', 97.0: 'Нет детей', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'DETI_3': {1.0: 'Есть дети до 6 лет включительно', 2.0: 'Есть дети от 7 до 17 лет включительно', 3.0: 'Есть дети 18 лет и старше', 97.0: 'Нет детей', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'DETI_4': {1.0: 'Есть дети до 6 лет включительно', 2.0: 'Есть дети от 7 до 17 лет включительно', 3.0: 'Есть дети 18 лет и старше', 97.0: 'Нет детей', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'DETI_5': {1.0: 'Есть дети до 6 лет включительно', 2.0: 'Есть дети от 7 до 17 лет включительно', 3.0: 'Есть дети 18 лет и старше', 97.0: 'Нет детей', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'DETI_6': {1.0: 'Есть дети до 6 лет включительно', 2.0: 'Есть дети от 7 до 17 лет включительно', 3.0: 'Есть дети 18 лет и старше', 97.0: 'Нет детей', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'PROF1': {1.0: 'Неработающий пенсионер (в том числе по инвалидности)', 2.0: 'Работающий пенсионер', 3.0: 'Неработающий учащийся, студент', 4.0: 'Работающий учащийся, студент', 5.0: 'Временно не работаю, безработный', 6.0: 'Нахожусь в декретном отпуске, отпуске по уходу за ребенком', 7.0: 'Работаю по договОру, контракту в найме (за исключением находящихся в декретном отпуске, подрабатывающих студентов, пе...', 8.0: 'Предприниматель, собственник бизнеса', 9.0: 'Самозанятый', 99.0: '(НЕ ЗАЧИТЫВАТЬ) Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...', 999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'}, 'PROF2': {1.0: 'Я работаю в КОММЕРЧЕСКОЙ организации, ее цель – получить прибыль (например, магазин, завод, фермерское хозяйство, АО/...', 2.0: 'Я работаю в БЮДЖЕТНОЙ организации, которая безвозмездно оказывает услуги населению (детский сад, общеобразовательная,...', 3.0: 'Я работаю в НЕКОММЕРЧЕСКОЙ организации, которая оказывает помощь населению (благотворительные фонды, центры поддержки...', 4.0: 'Работаю в органах власти, управления, судебных органах', 5.0: 'Работаю в правоохранительных органах, вооруженных силах, МЧС', 99.0: 'Затрудняюсь ответить/ отказ от ответа', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'}, 'PROF3': {1.0: 'Промышленность, производство (в т.ч. добывающие, обрабатывающие отрасли, энергетика) Включает в том числе: Завод, ком...', 2.0: 'Сельское, лесное хозяйство, охота, рыболовство и рыбоводство Включает в том числе: Фермерское хозяйство, скотобойни, ...', 3.0: 'Строительство Включает в том числе: архитектура, проектирование, дизайн интерьера', 4.0: 'Жилищно-коммунальное хозяйство Включает в том числе: водоканал, горгаз, вывоз мусора, котельная, сортировка и перераб...', 5.0: 'Образование, наука Включает в том числе: ясли, детский сад, школа, ССУЗ, вуз, научно-исследовательские институты, центры', 6.0: 'Здравоохранение Включает в том числе: поликлиники, медицинские центры, больницы, стационары, «Скорая помощь», санатории', 7.0: 'Социальные услуги, социальное обеспечение Включает в том числе: собес, пенсионный фонд, реабилитационный центр, центр...', 8.0: 'Культура, искусство, спорт Включает в том числе: дома культуры, дома народного творчества, музеи, библиотеки, концерт...', 9.0: 'Сфера отдыха и развлечений, туризм Включает в том числе: Парки, активный отдых, прокат (лодок, снаряжения), ярмарки, ...', 10.0: 'Государственное и муниципальное управление, в т.ч. - судебные органы Включает в том числе: Госслужба, администрации/п...', 11.0: 'Правоохранительные органы, силовые структуры, МЧС, военная служба Включает в том числе: Полиция, росгвардия, пожарно-...', 12.0: 'Средства массовой информации (в т.ч. журналистика, блогерство, реклама, СММ) Включает в том числе: Издательство печат...', 13.0: 'Информационные технологии, связь, интернет Включает в том числе: Программирование /создание программного обеспечения,...', 14.0: 'Торговля (оптовая, розничная, онлайн продажи; в т.ч. - недвижимость) Включает в том числе: Магазин, автосалон, аукцио...', 15.0: 'Финансовая и страховая деятельность, банковские услуги Включает в том числе: Банк, инвестиционный фонд, финансовая ар...', 16.0: 'Транспортировка и хранение (складское хозяйство) Включает в том числе: Перевозка грузов, ж/д, авиа, водный, космическ...', 17.0: 'Общественное питание, ресторанный и гостиничный бизнес Включает в том числе: Кафе, ресторан, доставка продуктов питан...', 18.0: 'Сфера услуг, сервиса, бытового обслуживания Включает в том числе: Прачечная/химчистка, ремонт мебели, часов, ювелирны...', 98.0: 'Другое (укажите)', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...', 999.0: 'Отказ от ответа'}}, value_labels={'labels0': {1.0: 'Мужской', 2.0: 'Женский'}, 'labels1': {1.0: 'Центральный федеральный округ', 2.0: 'Северо-Западный федеральный округ', 3.0: 'Южный федеральный округ', 4.0: 'Северо-Кавказский федеральный округ', 5.0: 'Приволжский федеральный округ', 6.0: 'Уральский федеральный округ', 7.0: 'Сибирский федеральный округ', 8.0: 'Дальневосточный федеральный округ'}, 'labels2': {1.0: 'Город с численностью жителей миллион и более человек', 2.0: 'Город с численностью от 500 тысяч до 950 тысяч', 3.0: 'Город с численностью от 100 тысяч до 500 тысяч', 4.0: 'Город с численностью от 50 тысяч до 100 тысяч', 5.0: 'Город с численностью менее 50 тысяч', 6.0: 'Поселок городского типа', 7.0: 'Село'}, 'labels3': {1.0: 'Скорее положительно (поясните, почему?)', 2.0: 'Скорее отрицательно (поясните, почему?)', 3.0: 'Скорее безразлично', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'labels4': {1.0: 'Бывает путают детей в роддамах / меняют', 2.0: 'В медицинских целях / выявление генетических болезней', 3.0: 'Важно для выплаты алиментов / избежание не выплаты алиментов', 4.0: 'Во избежание спорных моментов / юридические вопросы', 5.0: 'Для защиты ребенка и матери / безопасность', 6.0: 'Получение социальных выплат', 7.0: 'Определение отцовства / отец будет знать его ребенок или нет / знать, кто родитель / от кого ребенок', 8.0: 'Положительно отношусь / это правильно / полезно', 9.0: 'Если оба согласны, то пусть делают', 10.0: 'Есть случаи, когда отцы воспитывают не своих детей / женщины гуляют, обманывают', 11.0: 'Защита прав отцов', 12.0: 'Дети будут знать кто их родители', 13.0: 'Больше уверенности / доверия / если нечего скрывать / не будет сомнений', 14.0: 'Отцы должны принимать участие в жизни ребенка', 15.0: 'Меньше обмана / проблем', 16.0: 'Бывают разные ситуации', 17.0: 'Снимет кучу вопросов', 18.0: 'Родители будут знать, что это их ребенок', 19.0: 'Поможет в установлении личности', 20.0: 'Предотвратить измены / сохранение семей', 21.0: 'Предотвратить измены / сохранение семей', 98.0: 'Другое', 99.0: 'Затрудняюсь ответить'}, 'labels5': {1.0: 'В этом нет смысла / отрицательно отношусь', 2.0: 'Вмешательство в личную жизнь', 3.0: 'Есть доверие / уверенны друг в друге', 4.0: 'Трата бюджетных средств', 5.0: 'Сами должны решать нужен тест или нет / личное дело каждого', 6.0: 'Внесет разногласия в семью / увеличится количество разводов', 7.0: 'Не верю в корректность результата теста', 8.0: 'Дальнейшее использование данных / контроль над людьми', 9.0: 'Родители сами все знаю / мать знает, кто отец', 10.0: 'Против мучения ребенка', 11.0: 'Бывает суррогатное материнство', 12.0: 'Проводить только если необходимо / через суд', 13.0: 'Навредит ребенку и матери', 14.0: 'Главное ребенок родился / неважно чей', 98.0: 'Другое', 99.0: 'Затрудняюсь ответить'}, 'labels6': {1.0: 'Укреплять отношения в паре', 2.0: 'Ослаблять отношения', 3.0: 'Никак не влиять на отношения', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'labels7': {1.0: 'Согласился бы', 2.0: 'Скорее согласился бы', 3.0: 'Скорее не согласился бы', 4.0: 'Точно не согласился бы', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'labels8': {1.0: 'Продолжать воспитывать ребенка, так как важнее сложившиеся отношения, отец – тот, кто воспитал', 2.0: 'Прекратить участие в жизни ребенка, так как биологическое родство принципиально важно', 99.0: 'Затрудняюсь ответить', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'}, 'labels9': {1.0: 'Смотрю более четырех часов ежедневно', 2.0: 'Ежедневно менее четырех часов в день', 3.0: 'Несколько раз в неделю', 4.0: 'Несколько раз в месяц', 5.0: 'Редко, но не менее одного раза в полгода', 6.0: 'Не смотрю', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'}, 'labels10': {1.0: 'Провожу в интернете более четырех часов ежедневно', 2.0: 'Eжедневно менее четырех часов в день', 3.0: 'Несколько раз в неделю', 4.0: 'Несколько раз в месяц', 5.0: 'Редко, но не менее одного раза в полгода', 96.0: 'Не пользуюсь', 777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продо

In [11]:
meta.column_labels # выводит метки переменных

['Идентификатор респондента',
 'Пол',
 'Сколько полных лет Вам исполнилось?',
 'Федеральный округ',
 'Тип населенного пункта',
 'dnk1. Сменим тему. В России предложили ввести обязательную процедуру ДНК-тестирования в родильных домах с согласия обоих родителей. По мнению авторов, нововведение обеспечит правовую защиту детей с первых дней жизни, например, облегчит назначение выпла',
 'Скорее положительно (поясните, почему?)',
 'Скорее отрицательно (поясните, почему?)',
 'dnk2. Как Вы считаете, если ДНК-тест подтверждает отцовство, факт его проведения будет скорее…?',
 'dnk3. А Вы согласились бы на проведение такого теста при рождении ребенка или нет?',
 'dnk4. Представьте, что мужчина узнаёт, что ребенок, которого он воспитывал, не является его биологическим. Как, по Вашему мнению, ему следует поступить?',
 'TV. Поговорим немного о Вас. Скажите, пожалуйста, Вы смотрите телевизор или нет? Если смотрите, то как часто?',
 'd1. Скажите, пожалуйста, Вы пользуетесь интернетом? Если да, то как часто?',
 'EDU. Какое у Вас образование?',
 'DOHOD-0. Как бы Вы оценили в настоящее время материальное положение Вашей семьи – Вас и Ваших родственников, постоянно проживающих вместе с Вами?',
 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?',
 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?',
 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?',
 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?',
 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?',
 'DETI. Скажите, пожалуйста, есть ли у Вас дети или нет? И если есть, то какого они возраста?',
 'PROF_1. Скажите, пожалуйста, каково Ваше основное занятие в настоящий момент? Я зачитаю варианты ответов, а Вы выберите вариант, который подходит Вам.',
 'PROF_2. В нашей стране существуют организации разных видов. Сейчас я зачитаю несколько вариантов, а Вы скажите, какой из них лучше соответствует организации / предприятию, где Вы работаете.',
 'PROF_3. Скажите, к какой отрасли, сфере деятельности относится организация, в которой Вы работаете?',
 None]

In [12]:
meta.column_names # выводит имена переменных

['ID',
 'SEX',
 'AGE',
 'FO',
 'TIP',
 'dnk1',
 'dnk1_1d',
 'dnk1_2d',
 'dnk2',
 'dnk3',
 'dnk4',
 'TV',
 'd1',
 'EDU',
 'DOHOD_0',
 'DETI_1',
 'DETI_2',
 'DETI_3',
 'DETI_4',
 'DETI_5',
 'DETI_6',
 'PROF1',
 'PROF2',
 'PROF3',
 'weight1']

In [13]:
meta.value_labels # выводит значения переменных

{'labels0': {1.0: 'Мужской', 2.0: 'Женский'},
 'labels1': {1.0: 'Центральный федеральный округ',
  2.0: 'Северо-Западный федеральный округ',
  3.0: 'Южный федеральный округ',
  4.0: 'Северо-Кавказский федеральный округ',
  5.0: 'Приволжский федеральный округ',
  6.0: 'Уральский федеральный округ',
  7.0: 'Сибирский федеральный округ',
  8.0: 'Дальневосточный федеральный округ'},
 'labels2': {1.0: 'Город с численностью жителей миллион и более человек',
  2.0: 'Город с численностью от 500 тысяч до 950 тысяч',
  3.0: 'Город с численностью от 100 тысяч до 500 тысяч',
  4.0: 'Город с численностью от 50 тысяч до 100 тысяч',
  5.0: 'Город с численностью менее 50 тысяч',
  6.0: 'Поселок городского типа',
  7.0: 'Село'},
 'labels3': {1.0: 'Скорее положительно (поясните, почему?)',
  2.0: 'Скорее отрицательно (поясните, почему?)',
  3.0: 'Скорее безразлично',
  99.0: 'Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'},
 'labels4': {1.0: 'Бывает путают детей в роддамах / меняют',
  2.0: 'В медицинских целях / выявление генетических болезней',
  3.0: 'Важно для выплаты алиментов / избежание не выплаты алиментов',
  4.0: 'Во избежание спорных моментов / юридические вопросы',
  5.0: 'Для защиты ребенка и матери / безопасность',
  6.0: 'Получение социальных выплат',
  7.0: 'Определение отцовства / отец будет знать его ребенок или нет / знать, кто родитель / от кого ребенок',
  8.0: 'Положительно отношусь / это правильно / полезно',
  9.0: 'Если оба согласны, то пусть делают',
  10.0: 'Есть случаи, когда отцы воспитывают не своих детей / женщины гуляют, обманывают',
  11.0: 'Защита прав отцов',
  12.0: 'Дети будут знать кто их родители',
  13.0: 'Больше уверенности / доверия / если нечего скрывать / не будет сомнений',
  14.0: 'Отцы должны принимать участие в жизни ребенка',
  15.0: 'Меньше обмана / проблем',
  16.0: 'Бывают разные ситуации',
  17.0: 'Снимет кучу вопросов',
  18.0: 'Родители будут знать, что это их ребенок',
  19.0: 'Поможет в установлении личности',
  20.0: 'Предотвратить измены / сохранение семей',
  21.0: 'Предотвратить измены / сохранение семей',
  98.0: 'Другое',
  99.0: 'Затрудняюсь ответить'},
 'labels5': {1.0: 'В этом нет смысла / отрицательно отношусь',
  2.0: 'Вмешательство в личную жизнь',
  3.0: 'Есть доверие / уверенны друг в друге',
  4.0: 'Трата бюджетных средств',
  5.0: 'Сами должны решать нужен тест или нет / личное дело каждого',
  6.0: 'Внесет разногласия в семью / увеличится количество разводов',
  7.0: 'Не верю в корректность результата теста',
  8.0: 'Дальнейшее использование данных / контроль над людьми',
  9.0: 'Родители сами все знаю / мать знает, кто отец',
  10.0: 'Против мучения ребенка',
  11.0: 'Бывает суррогатное материнство',
  12.0: 'Проводить только если необходимо / через суд',
  13.0: 'Навредит ребенку и матери',
  14.0: 'Главное ребенок родился / неважно чей',
  98.0: 'Другое',
  99.0: 'Затрудняюсь ответить'},
 'labels6': {1.0: 'Укреплять отношения в паре',
  2.0: 'Ослаблять отношения',
  3.0: 'Никак не влиять на отношения',
  99.0: 'Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'},
 'labels7': {1.0: 'Согласился бы',
  2.0: 'Скорее согласился бы',
  3.0: 'Скорее не согласился бы',
  4.0: 'Точно не согласился бы',
  99.0: 'Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'},
 'labels8': {1.0: 'Продолжать воспитывать ребенка, так как важнее сложившиеся отношения, отец – тот, кто воспитал',
  2.0: 'Прекратить участие в жизни ребенка, так как биологическое родство принципиально важно',
  99.0: 'Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью. Отметить, только при явно выраженном отказе; не отмечать...'},
 'labels9': {1.0: 'Смотрю более четырех часов ежедневно',
  2.0: 'Ежедневно менее четырех часов в день',
  3.0: 'Несколько раз в неделю',
  4.0: 'Несколько раз в месяц',
  5.0: 'Редко, но не менее одного раза в полгода',
  6.0: 'Не смотрю',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'},
 'labels10': {1.0: 'Провожу в интернете более четырех часов ежедневно',
  2.0: 'Eжедневно менее четырех часов в день',
  3.0: 'Несколько раз в неделю',
  4.0: 'Несколько раз в месяц',
  5.0: 'Редко, но не менее одного раза в полгода',
  96.0: 'Не пользуюсь',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'},
 'labels11': {1.0: '(НЕ ЗАЧИТЫВАТЬ) Нет основного общего образования: не окончил 9 (раньше 8) классов',
  2.0: 'Основное общее образование: окончил 9 (раньше 8) классов',
  3.0: 'Среднее общее (10 или 11 классов школы с аттестатом)',
  4.0: 'Среднее профессиональное (техникум, колледж, ПТУ)',
  5.0: 'Незаконченное высшее (с 3-го курса вуза) или законченное высшее',
  6.0: 'Два и более высших образования, ученая степень кандидата или доктора наук',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...',
  999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'},
 'labels12': {1.0: 'Очень хорошее',
  2.0: 'Хорошее',
  3.0: 'Среднее',
  4.0: 'Плохое',
  5.0: 'Очень плохое',
  99.0: 'Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'},
 'labels13': {1.0: 'Есть дети до 6 лет включительно',
  2.0: 'Есть дети от 7 до 17 лет включительно',
  3.0: 'Есть дети 18 лет и старше',
  97.0: 'Нет детей',
  999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'},
 'labels14': {1.0: 'Есть дети до 6 лет включительно',
  2.0: 'Есть дети от 7 до 17 лет включительно',
  3.0: 'Есть дети 18 лет и старше',
  97.0: 'Нет детей',
  999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'},
 'labels15': {1.0: 'Неработающий пенсионер (в том числе по инвалидности)',
  2.0: 'Работающий пенсионер',
  3.0: 'Неработающий учащийся, студент',
  4.0: 'Работающий учащийся, студент',
  5.0: 'Временно не работаю, безработный',
  6.0: 'Нахожусь в декретном отпуске, отпуске по уходу за ребенком',
  7.0: 'Работаю по договОру, контракту в найме (за исключением находящихся в декретном отпуске, подрабатывающих студентов, пе...',
  8.0: 'Предприниматель, собственник бизнеса',
  9.0: 'Самозанятый',
  99.0: '(НЕ ЗАЧИТЫВАТЬ) Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...',
  999.0: '(НЕ ЗАЧИТЫВАТЬ) Отказ от ответа'},
 'labels16': {1.0: 'Я работаю в КОММЕРЧЕСКОЙ организации, ее цель – получить прибыль (например, магазин, завод, фермерское хозяйство, АО/...',
  2.0: 'Я работаю в БЮДЖЕТНОЙ организации, которая безвозмездно оказывает услуги населению (детский сад, общеобразовательная,...',
  3.0: 'Я работаю в НЕКОММЕРЧЕСКОЙ организации, которая оказывает помощь населению (благотворительные фонды, центры поддержки...',
  4.0: 'Работаю в органах власти, управления, судебных органах',
  5.0: 'Работаю в правоохранительных органах, вооруженных силах, МЧС',
  99.0: 'Затрудняюсь ответить/ отказ от ответа',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...'},
 'labels17': {1.0: 'Промышленность, производство (в т.ч. добывающие, обрабатывающие отрасли, энергетика) Включает в том числе: Завод, ком...',
  2.0: 'Сельское, лесное хозяйство, охота, рыболовство и рыбоводство Включает в том числе: Фермерское хозяйство, скотобойни, ...',
  3.0: 'Строительство Включает в том числе: архитектура, проектирование, дизайн интерьера',
  4.0: 'Жилищно-коммунальное хозяйство Включает в том числе: водоканал, горгаз, вывоз мусора, котельная, сортировка и перераб...',
  5.0: 'Образование, наука Включает в том числе: ясли, детский сад, школа, ССУЗ, вуз, научно-исследовательские институты, центры',
  6.0: 'Здравоохранение Включает в том числе: поликлиники, медицинские центры, больницы, стационары, «Скорая помощь», санатории',
  7.0: 'Социальные услуги, социальное обеспечение Включает в том числе: собес, пенсионный фонд, реабилитационный центр, центр...',
  8.0: 'Культура, искусство, спорт Включает в том числе: дома культуры, дома народного творчества, музеи, библиотеки, концерт...',
  9.0: 'Сфера отдыха и развлечений, туризм Включает в том числе: Парки, активный отдых, прокат (лодок, снаряжения), ярмарки, ...',
  10.0: 'Государственное и муниципальное управление, в т.ч. - судебные органы Включает в том числе: Госслужба, администрации/п...',
  11.0: 'Правоохранительные органы, силовые структуры, МЧС, военная служба Включает в том числе: Полиция, росгвардия, пожарно-...',
  12.0: 'Средства массовой информации (в т.ч. журналистика, блогерство, реклама, СММ) Включает в том числе: Издательство печат...',
  13.0: 'Информационные технологии, связь, интернет Включает в том числе: Программирование /создание программного обеспечения,...',
  14.0: 'Торговля (оптовая, розничная, онлайн продажи; в т.ч. - недвижимость) Включает в том числе: Магазин, автосалон, аукцио...',
  15.0: 'Финансовая и страховая деятельность, банковские услуги Включает в том числе: Банк, инвестиционный фонд, финансовая ар...',
  16.0: 'Транспортировка и хранение (складское хозяйство) Включает в том числе: Перевозка грузов, ж/д, авиа, водный, космическ...',
  17.0: 'Общественное питание, ресторанный и гостиничный бизнес Включает в том числе: Кафе, ресторан, доставка продуктов питан...',
  18.0: 'Сфера услуг, сервиса, бытового обслуживания Включает в том числе: Прачечная/химчистка, ремонт мебели, часов, ювелирны...',
  98.0: 'Другое (укажите)',
  99.0: 'Затрудняюсь ответить',
  777.0: '(НЕ ЗАЧИТЫВАТЬ!!!) Респондент отказался продолжать интервью.Отметить, только при явно выраженном отказе; не отмечать,...',
  999.0: 'Отказ от ответа'}}

In [14]:
meta.variable_measure # выводит тип шкалы

{'ID': 'nominal',
 'SEX': 'nominal',
 'AGE': 'nominal',
 'FO': 'nominal',
 'TIP': 'nominal',
 'dnk1': 'nominal',
 'dnk1_1d': 'nominal',
 'dnk1_2d': 'nominal',
 'dnk2': 'nominal',
 'dnk3': 'nominal',
 'dnk4': 'nominal',
 'TV': 'nominal',
 'd1': 'nominal',
 'EDU': 'nominal',
 'DOHOD_0': 'nominal',
 'DETI_1': 'nominal',
 'DETI_2': 'nominal',
 'DETI_3': 'nominal',
 'DETI_4': 'nominal',
 'DETI_5': 'nominal',
 'DETI_6': 'nominal',
 'PROF1': 'nominal',
 'PROF2': 'nominal',
 'PROF3': 'nominal',
 'weight1': 'nominal'}

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       1608 non-null   object
 1   SEX      1608 non-null   float64
 2   AGE      1608 non-null   float64
 3   FO       1608 non-null   float64
 4   TIP      1608 non-null   float64
 5   dnk1     1608 non-null   float64
 6   dnk1_1d  838 non-null    float64
 7   dnk1_2d  275 non-null    float64
 8   dnk2     1608 non-null   float64
 9   dnk3     1608 non-null   float64
 10  dnk4     1608 non-null   float64
 11  TV       1608 non-null   float64
 12  d1       1608 non-null   float64
 13  EDU      1608 non-null   float64
 14  DOHOD_0  1608 non-null   float64
 15  DETI_1   1608 non-null   float64
 16  DETI_2   240 non-null    float64
 17  DETI_3   16 non-null     float64
 18  DETI_4   0 non-null      float64
 19  DETI_5   0 non-null      float64
 20  DETI_6   0 non-null      float64
 21  PROF1    1608 non-null   float64
 22  PROF2    839 non-null    float64
 23  PROF3    1059 non-null   float64
 24  weight1  1608 non-null   float64
dtypes: float64(24), object(1)
memory usage: 314.2+ KB

In [22]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       1608 non-null   object
 1   SEX      1608 non-null   category
 2   AGE      1608 non-null   float64
 3   FO       1608 non-null   category
 4   TIP      1608 non-null   category
 5   dnk1     1608 non-null   category
 6   dnk1_1d  838 non-null    category
 7   dnk1_2d  275 non-null    category
 8   dnk2     1608 non-null   category
 9   dnk3     1608 non-null   category
 10  dnk4     1608 non-null   category
 11  TV       1608 non-null   category
 12  d1       1608 non-null   category
 13  EDU      1608 non-null   category
 14  DOHOD_0  1608 non-null   category
 15  DETI_1   1608 non-null   category
 16  DETI_2   240 non-null    category
 17  DETI_3   16 non-null     category
 18  DETI_4   0 non-null      category
 19  DETI_5   0 non-null      category
 20  DETI_6   0 non-null      category
 21  PROF1    1608 non-null   category
 22  PROF2    839 non-null    category
 23  PROF3    1059 non-null   category
 24  weight1  1608 non-null   float64
dtypes: category(22), float64(2), object(1)
memory usage: 78.4+ KB

In [19]:
df['dnk1'].unique()

array([ 1.,  2., 99.,  3.])

In [28]:
df['dnk1'].value_counts().sort_index() #

dnk1
1.0     840
2.0     277
3.0     380
99.0    111
Name: count, dtype: int64

In [29]:
df['dnk1'].value_counts().sort_values() #

dnk1
99.0    111
2.0     277
3.0     380
1.0     840
Name: count, dtype: int64

In [21]:
df_1['dnk1'].value_counts()

dnk1
Скорее положительно (поясните, почему?)    840
Скорее безразлично                         380
Скорее отрицательно (поясните, почему?)    277
Затрудняюсь ответить                       111
Name: count, dtype: int64

In [25]:
df_1['dnk1'].value_counts(normalize = True).round(2)*100

dnk1
Скорее положительно (поясните, почему?)    52.0
Скорее безразлично                         24.0
Скорее отрицательно (поясните, почему?)    17.0
Затрудняюсь ответить                        7.0
Name: proportion, dtype: float64

In [31]:
df_1['dnk1_1d'].unique()

['Для защиты ребенка и матери / безопасность', NaN, 'Во избежание спорных моментов / юридические в..., 'Бывает путают детей в роддамах / меняют', 'Снимет кучу вопросов', ..., 'Дети будут знать кто их родители', 'Другое', 'Защита прав отцов', 'Получение социальных выплат', 'Затрудняюсь ответить']
Length: 23
Categories (22, object): ['Больше уверенности / доверия / если нечего ск..., 'Бывает путают детей в роддамах / меняют',
                          'Бывают разные ситуации', 'В медицинских целях / выявление генетических ..., ...,
                          'Поможет в установлении личности', 'Предотвратить измены / сохранение семей',
                          'Родители будут знать, что это их ребенок', 'Снимет кучу вопросов']

In [33]:
df_1['dnk1_1d'].value_counts()

dnk1_1d
Определение отцовства / отец будет знать его ребенок или нет / знать, кто родитель / от кого ребенок    132
Есть случаи, когда отцы воспитывают не своих детей / женщины гуляют, обманывают                          75
Положительно отношусь / это правильно / полезно                                                          75
Во избежание спорных моментов / юридические вопросы                                                      69
Бывает путают детей в роддамах / меняют                                                                  62
Больше уверенности / доверия / если нечего скрывать / не будет сомнений                                  59
Меньше обмана / проблем                                                                                  53
Для защиты ребенка и матери / безопасность                                                               43
Отцы должны принимать участие в жизни ребенка                                                            30
Предотвратить измены / сохранение семей                                                                  28
Другое                                                                                                   28
Поможет в установлении личности                                                                          27
Снимет кучу вопросов                                                                                     23
Важно для выплаты алиментов / избежание не выплаты алиментов                                             20
Родители будут знать, что это их ребенок                                                                 17
Если оба согласны, то пусть делают                                                                       17
Получение социальных выплат                                                                              16
В медицинских целях / выявление генетических болезней                                                    15
Защита прав отцов                                                                                        15
Бывают разные ситуации                                                                                   14
Дети будут знать кто их родители                                                                         13
Затрудняюсь ответить                                                                                      7
Name: count, dtype: int64

In [43]:
cros_1 = pd.crosstab (df_1['SEX'], df_1['dnk1'], margins=True)

In [41]:
pd.crosstab(df_1['SEX'], df_1['dnk1'], margins=True, normalize= True).round(3)*100

dnk1,Затрудняюсь ответить,Скорее безразлично,"Скорее отрицательно (поясните, почему?)","Скорее положительно (поясните, почему?)",All
SEX,,,,,
Женский,3.0,10.9,7.8,19.0,40.8
Мужской,3.9,12.7,9.4,33.2,59.2
All,6.9,23.6,17.2,52.2,100.0

In [46]:
chi2_contingency(cros_1) # тест на значимость различий хи-квадрат Пирсона

Chi2ContingencyResult(statistic=np.float64(14.02050228560343), pvalue=np.float64(0.08123259451042934), dof=8, expected_freq=array([[  45.28358209,  155.02487562,  113.00497512,  342.68656716,
         656.        ],
       [  65.71641791,  224.97512438,  163.99502488,  497.31343284,
         952.        ],
       [ 111.        ,  380.        ,  277.        ,  840.        ,
        1608.        ]]))