<a href="https://colab.research.google.com/github/Almodovare/Notebooks/blob/%D0%90%D0%BD%D0%94%D0%B0%D0%BD_%D0%9C%D0%B0%D0%B3_26/%D0%A3%D1%80%D0%BE%D0%BA_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Загрузим данные

In [ ]:
import pandas as pd # установим библиотеку

In [ ]:
!git clone https://github.com/Almodovare/Training_Data.git # клонируем репозиторий с Git Hub

Cloning into 'Training_Data'...
remote: Enumerating objects: 177, done.
remote: Total 177 (delta 0), reused 0 (delta 0), pack-reused 177 (from 2)
Receiving objects: 100% (177/177), 34.81 MiB | 18.55 MiB/s, done.
Resolving deltas: 100% (51/51), done.

In [ ]:
df = pd.read_csv('/content/Training_Data/mtcars.csv') # загрузим данные
df

,Unnamed: 0,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
0,0,18.0,8,307.0,130.0,3504.0,12.0,70,1
1,1,15.0,8,350.0,165.0,3693.0,11.5,70,1
2,2,18.0,8,318.0,150.0,3436.0,11.0,70,1
3,3,16.0,8,304.0,150.0,3433.0,12.0,70,1
4,4,17.0,8,302.0,140.0,3449.0,10.5,70,1
...,...,...,...,...,...,...,...,...,...
393,393,27.0,4,140.0,86.0,2790.0,15.6,82,1
394,394,44.0,4,97.0,52.0,2130.0,24.6,82,2
395,395,32.0,4,135.0,84.0,2295.0,11.6,82,1
396,396,28.0,4,120.0,79.0,2625.0,18.6,82,1
397,397,31.0,4,119.0,82.0,2720.0,19.4,82,1

#Описание набора данных

In [ ]:
df.shape # возвраращает форму набора данных (кол-во строчек;кол-во столбцов)

(398, 9)

In [ ]:
df.info() # возвращает метаинформацию о наборе данных

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    398 non-null    int64
 1   MPG           398 non-null    float64
 2   Cylinders     398 non-null    int64
 3   Displacement  398 non-null    float64
 4   Horsepower    392 non-null    float64
 5   Weight        398 non-null    float64
 6   Acceleration  398 non-null    float64
 7   Model Year    398 non-null    int64
 8   Origin        398 non-null    int64
dtypes: float64(5), int64(4)
memory usage: 28.1 KB

In [ ]:
df.describe().round(1) #метод .describe() выводит описательные статистики все сразу
# метод .round() округляет до указанного количества знаков

,Unnamed: 0,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
count,398.0,398.0,398.0,398.0,392.0,398.0,398.0,398.0,398.0
mean,198.5,23.5,5.5,193.4,104.5,2970.4,15.6,76.0,1.6
std,115.0,7.8,1.7,104.3,38.5,846.8,2.8,3.7,0.8
min,0.0,9.0,3.0,68.0,46.0,1613.0,8.0,70.0,1.0
25%,99.2,17.5,4.0,104.2,75.0,2223.8,13.8,73.0,1.0
50%,198.5,23.0,4.0,148.5,93.5,2803.5,15.5,76.0,1.0
75%,297.8,29.0,8.0,262.0,126.0,3608.0,17.2,79.0,2.0
max,397.0,46.6,8.0,455.0,230.0,5140.0,24.8,82.0,3.0

In [ ]:
df.mean() # возвращает среднее арифметическое значение

Unnamed: 0       198.500000
MPG               23.514573
Cylinders          5.454774
Displacement     193.425879
Horsepower       104.469388
Weight          2970.424623
Acceleration      15.568090
Model Year        76.010050
Origin             1.572864
dtype: float64

In [ ]:
df.MPG.mean().round(2) # можно вывести среднее для отдельного столбца

np.float64(23.51)

In [ ]:
df.Displacement.mean().round(3)

np.float64(193.426)

In [ ]:
df.std() # расчет среднего квадратического отклонения

Unnamed: 0      115.036951
MPG               7.815984
Cylinders         1.701004
Displacement    104.269838
Horsepower       38.491160
Weight          846.841774
Acceleration      2.757689
Model Year        3.697627
Origin            0.802055
dtype: float64

In [ ]:
df.var() # расчет дисперсии

Unnamed: 0       13233.500000
MPG                 61.089611
Cylinders            2.893415
Displacement     10872.199152
Horsepower        1481.569393
Weight          717140.990526
Acceleration         7.604848
Model Year          13.672443
Origin               0.643292
dtype: float64

In [ ]:
df.median() # расчет медианы

Unnamed: 0       198.5
MPG               23.0
Cylinders          4.0
Displacement     148.5
Horsepower        93.5
Weight          2803.5
Acceleration      15.5
Model Year        76.0
Origin             1.0
dtype: float64

In [ ]:
df.max() # расчет максимального значения

In [ ]:
df.min() # расчет минимального значения

In [ ]:
df.count() # расчет количества наблюдений (n)

Unnamed: 0      398
MPG             398
Cylinders       398
Displacement    398
Horsepower      392
Weight          398
Acceleration    398
Model Year      398
Origin          398
dtype: int64

In [ ]:
df.quantile(0.25) #расчет квантиля, например, первого квартиля
# в качестве аргумента может быть указано другое число, например,
# для Q3 = 0.75

Unnamed: 0        39.7
MPG               14.0
Cylinders          4.0
Displacement      90.0
Horsepower        67.0
Weight          1988.5
Acceleration      12.0
Model Year        71.0
Origin             1.0
Name: 0.1, dtype: float64

In [ ]:
df.sum() # расчет суммы значений переменной

Unnamed: 0        79003.0
MPG                9358.8
Cylinders          2171.0
Displacement      76983.5
Horsepower        40952.0
Weight          1182229.0
Acceleration       6196.1
Model Year        30252.0
Origin              626.0
dtype: float64

In [ ]:
df.skew() # коэффициент асимметрии. Чем он ближе к 0, тем более симметричное
# распределение

Unnamed: 0      0.000000
MPG             0.457066
Cylinders       0.526922
Displacement    0.719645
Horsepower      1.087326
Weight          0.531063
Acceleration    0.278777
Model Year      0.011535
Origin          0.923776
dtype: float64

In [ ]:
df.kurt() # коэффицикент эксцесса. Чем ближе к 0, тем распределение ближе к нормальному
# по остроте вершины

Unnamed: 0     -1.200000
MPG            -0.510781
Cylinders      -1.376662
Displacement   -0.746597
Horsepower      0.696947
Weight         -0.785529
Acceleration    0.419497
Model Year     -1.181232
Origin         -0.817597
dtype: float64

# Уникальные значения

In [ ]:
df['Model Year'].unique() # просмотр уникальных значений переменной

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [ ]:
df['Model Year'].nunique() # количество уникальных значений

13

In [ ]:
df['Displacement'].nunique()

82

In [ ]:
uniq = df['Model Year'].unique()

In [ ]:
df['Model Year'].value_counts() # выводит таблицу частот для уникальных значений

Model Year
73    40
78    36
76    34
82    31
75    30
80    29
79    29
81    29
70    29
71    28
72    28
77    28
74    27
Name: count, dtype: int64

In [ ]:
df['Model Year'].value_counts().sort_index() # сортировка по варьирующей переменной

Model Year
70    29
71    28
72    28
73    40
74    27
75    30
76    34
77    28
78    36
79    29
80    29
81    29
82    31
Name: count, dtype: int64

In [ ]:
df['Model Year'].value_counts().sort_values() # сортировка по частоте

Model Year
74    27
72    28
71    28
77    28
79    29
81    29
80    29
70    29
75    30
82    31
76    34
78    36
73    40
Name: count, dtype: int64

In [ ]:
df.columns # выводит название колонок

Index(['Unnamed: 0', 'MPG', 'Cylinders', 'Displacement', 'Horsepower',
       'Weight', 'Acceleration', 'Model Year', 'Origin'],
      dtype='object')

# Пропущенные значения

In [ ]:
# Идентификация пропусков осуществляется с помощью метода .isna()
df.MPG.isna()

0      False
1      False
2      False
3      False
4      False
       ...
393    False
394    False
395    False
396    False
397    False
Name: MPG, Length: 398, dtype: bool

In [ ]:
df.MPG.isna().sum() # подсчет количества True, то есть количества пропусков

np.int64(0)

In [ ]:
df.isna().sum()

Unnamed: 0      0
MPG             0
Cylinders       0
Displacement    0
Horsepower      6
Weight          0
Acceleration    0
Model Year      0
Origin          0
dtype: int64

In [ ]:
df.Horsepower = df.Horsepower.fillna(df.Horsepower.mean()) # заполнение пропущенных значений
#в качестве аргумента указывается значение, которым заполняются пропуски

In [ ]:
df.Horsepower.isna().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    398 non-null    int64
 1   MPG           398 non-null    float64
 2   Cylinders     398 non-null    int64
 3   Displacement  398 non-null    float64
 4   Horsepower    398 non-null    float64
 5   Weight        398 non-null    float64
 6   Acceleration  398 non-null    float64
 7   Model Year    398 non-null    int64
 8   Origin        398 non-null    int64
dtypes: float64(5), int64(4)
memory usage: 28.1 KB

# Удаление и добавление столбцов

In [ ]:
df["Total"] = df.MPG * df.Horsepower # добавление столбца

In [ ]:
df.columns

Index(['Unnamed: 0', 'MPG', 'Cylinders', 'Displacement', 'Horsepower',
       'Weight', 'Acceleration', 'Model Year', 'Origin', 'Total'],
      dtype='object')

In [ ]:
df.sample(4)

,Unnamed: 0,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin,Total
68,68,13.0,8,350.0,155.0,4502.0,13.5,72,1,2015.0
4,4,17.0,8,302.0,140.0,3449.0,10.5,70,1,2380.0
12,12,15.0,8,400.0,150.0,3761.0,9.5,70,1,2250.0
396,396,28.0,4,120.0,79.0,2625.0,18.6,82,1,2212.0

In [ ]:
df.drop('Unnamed: 0', axis = 1) # при удалении столбца в качестве аргументов указывается наименование столбца и ось ( axis).
# Если axis =0, то удалятся строчки, если axis =1 - столбцы

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin,Total
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,2340.0
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,2475.0
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,2700.0
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,2400.0
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,2380.0
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790.0,15.6,82,1,2322.0
394,44.0,4,97.0,52.0,2130.0,24.6,82,2,2288.0
395,32.0,4,135.0,84.0,2295.0,11.6,82,1,2688.0
396,28.0,4,120.0,79.0,2625.0,18.6,82,1,2212.0
397,31.0,4,119.0,82.0,2720.0,19.4,82,1,2542.0